<a href="https://colab.research.google.com/github/stefanymarinho/ConectaMundo_stefany/blob/main/C%C3%B3pia_de_UNIDADE_1_lista_exercicios_percepcao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lista de exercícios de percepção — Unidade 1

**Disciplina:** Gestão e Qualidade de Software  
**Formato:** Google Colab

Esta lista foi baseada nas três aulas da Unidade 1: cultura DevOps e integração contínua; construção de pipelines CI/CD; métricas e Quality Gates.

O código deste notebook é apenas um simulador curto. A avaliação principal não será pela quantidade de código escrito. Será pela sua capacidade de prever, alterar, observar, comparar e explicar o comportamento do processo.

## Como fazer e entregar

Em cada exercício:

1. escreva sua previsão antes de executar a alteração;
2. altere somente os dados ou parâmetros solicitados;
3. execute e compare o resultado com sua previsão;
4. explique a causa da mudança e uma consequência para a equipe ou para o produto.

Entregue este notebook com o código executado, as tabelas geradas e suas respostas em células Markdown. Não entregue apenas o resultado PASSOU ou FALHOU.

Se usar uma ferramenta de IA, registre no final onde usou e como conferiu a resposta. Você deverá conseguir explicar todas as alterações entregues.

In [ ]:
import pandas as pd

pd.set_option('display.max_columns', None)
print('Ambiente pronto.')

Ambiente pronto.


## Exercício 1 — DevOps, CALMS e pirâmide de testes

Observe as situações abaixo. Para cada uma, escreva a categoria mais adequada e justifique em uma frase.

Use os pilares CALMS — Cultura, Automação, Lean, Medição e Sharing — e os níveis da pirâmide de testes — unitário, integração e ponta a ponta.

Antes de executar a tabela, preencha mentalmente suas classificações. Depois altere os campos categoria e justificativa no código.

In [ ]:
import pandas as pd

situacoes = [
    {
        'situacao': 'A equipe compartilha um post-mortem sem procurar culpados.',
        'categoria': 'Cultura/Sharing  ',
        'justificativa': 'Foca no aprendizado coletivo e na cultura blameless',
    },
    {
        'situacao': 'O pipeline executa os testes automaticamente a cada Pull Request.',
        'categoria': 'Automação',
        'justificativa': 'Automatiza a validação contínua de código sem intervenção humana',
    },
    {
        'situacao': 'A equipe prefere entregar pequenas mudanças diariamente.',
        'categoria': 'Lean',
        'justificativa': 'Parcela as  entregas para para diminuir os riscos/despedicios ',
    },
    {
        'situacao': 'Uma função de cálculo é testada isoladamente.',
        'categoria': 'Teste Unitário',
        'justificativa': 'Valida a função de forma isolada e rápida',
    },
    {
        'situacao': 'O contrato entre uma API e seu consumidor é verificado.',
        'categoria': 'Teste de Integração',
        'justificativa': 'Verifica a comunicação e interface/contrato entre dois componentes distintos',
    },
    {
        'situacao': 'O fluxo completo de compra é executado pela interface.',
        'categoria': 'Ponta a Ponta',
        'justificativa': 'Valida a jornada do usuário do início ao fim simulando o ambiente real',
    },
]

tabela_situacoes = pd.DataFrame(situacoes)
display(tabela_situacoes)

,situacao,categoria,justificativa
0,A equipe compartilha um post-mortem sem procur...,Cultura/Sharing,Foca no aprendizado coletivo e na cultura blam...
1,O pipeline executa os testes automaticamente a...,Automação,Automatiza a validação contínua de código sem ...
2,A equipe prefere entregar pequenas mudanças di...,Lean,Parcela as entregas para para diminuir os ris...
3,Uma função de cálculo é testada isoladamente.,Teste Unitário,Valida a função de forma isolada e rápida
4,O contrato entre uma API e seu consumidor é ve...,Teste de Integração,Verifica a comunicação e interface/contrato en...
5,O fluxo completo de compra é executado pela in...,Ponta a Ponta,Valida a jornada do usuário do início ao fim s...


### Sua análise

1. Acrescente uma situação criada por você e classifique-a.
2. Escolha uma situação e explique o que poderia acontecer se ela fosse ignorada.
3. Diga qual mudança teria maior efeito imediato: automatizar um teste, reduzir o tamanho das entregas ou melhorar o compartilhamento entre Dev e Ops. Justifique considerando o contexto, não existe resposta automática.

**Entregável 1:** tabela preenchida com sete situações [✅
] e uma análise de 5 a 8 linhas[✅].

Analise

Situação criada: "A equipe monitora o tempo de resposta das requisições em produção via dashboard."

Classificação: Medição (CALMS).

Justificativa: Trata da coleta e observabilidade de dados reais de uso para orientar melhorias contínuas e tomadas de decisão.

Análise de Impacto (Se uma situação for ignorada):
Se a situação "A equipe compartilha um post-mortem sem procurar culpados" for ignorada e a empresa adotar uma cultura de culpar indivíduos, os colaboradores passarão a esconder falhas, atrasar incidentes e evitar inovações por medo de punição. Sem transparência, a causa-raiz dos problemas nunca é corrigida e as falhas voltam a ocorrer repetidamente no sistema.

Análise do Maior Efeito Imediato:
A mudança de reduzir o tamanho das entregas (Lean) tende a ter o maior efeito transformador imediato na dinâmica da equipe. Embora a automação de testes traga velocidade técnica e o compartilhamento fortaleça a cultura, trabalhar com lotes menores (entregas diárias) reduz drasticamente a complexidade das integrações, facilita a identificação de bugs e diminui o tempo de recuperação quando ocorrem falhas. Lotes pequenos geram um ciclo de feedback muito mais rápido, forçando naturalmente a equipe a buscar automação e a se comunicar melhor no dia a dia.


## Exercício 2 — regressão, testes e Fail-Fast

O código abaixo representa uma regra de desconto e uma pequena suíte de testes. Não reescreva a solução. Primeiro registre qual teste você acha que falhará quando a regra for alterada.

Depois altere somente a taxa do cupom DEVOPS20 de 20% para 30%, execute a suíte e observe onde o pipeline para. Em seguida, corrija a regra e execute novamente.

In [ ]:
def calcular_valor_final(valor_base, cupom=None, vip=False):
    if valor_base <= 0:
        raise ValueError('O valor deve ser positivo.')

    taxa_desconto = 0.0
    if cupom == 'DEVOPS20':
        taxa_desconto = 0.30  # ALTERE SOMENTE ESTA TAXA

    if vip:
        taxa_desconto += 0.05

    taxa_desconto = min(taxa_desconto, 0.25)
    return round(valor_base * (1.0 - taxa_desconto), 2)


testes = [
    {'nome': 'sem desconto', 'chamada': lambda: calcular_valor_final(100.0), 'esperado': 100.0},
    {'nome': 'cupom de 20%', 'chamada': lambda: calcular_valor_final(100.0, cupom='DEVOPS20'), 'esperado': 80.0},
    {'nome': 'cupom e VIP com teto', 'chamada': lambda: calcular_valor_final(100.0, cupom='DEVOPS20', vip=True), 'esperado': 75.0},
    {'nome': 'valor inválido', 'chamada': lambda: calcular_valor_final(0.0), 'esperado': 'ValueError'},
]

resultados = []
for teste in testes:
    try:
        obtido = teste['chamada']()
    except Exception as erro:
        obtido = type(erro).__name__

    passou = obtido == teste['esperado']
    resultados.append({
        'teste': teste['nome'],
        'esperado': teste['esperado'],
        'obtido': obtido,
        'status': 'PASSOU' if passou else 'FALHOU',
    })
    print(teste['nome'], '->', 'PASSOU' if passou else 'FALHOU')
    if not passou:
        print('FAIL-FAST: a execução foi interrompida neste teste.')
        break

display(pd.DataFrame(resultados))

sem desconto -> PASSOU
cupom de 20% -> FALHOU
FAIL-FAST: a execução foi interrompida neste teste.


,teste,esperado,obtido,status
0,sem desconto,100.0,100.0,PASSOU
1,cupom de 20%,80.0,75.0,FALHOU


### Sua análise

Antes da alteração, escreva uma previsão com: primeiro teste que falhará, testes que deixarão de executar e motivo esperado.

Antes da Execução:

Primeiro teste que falhará: cupom de 20%.

Testes que deixarão de executar: cupom e VIP com teto e valor inválido.

Motivo esperado: Ao alterar a taxa de desconto de 0.20 para 0.30, a função retornará 100.0×(1.0−0.30)=70.0. Como o teste cupom de 20% espera o valor obtido de 80.0, haverá divergência. O pipeline será interrompido imediatamente no segundo teste devido à lógica de interrupção (Fail-Fast).

Depois da execução, compare sua previsão com o resultado. Explique:

- por que uma alteração de 20% para 30% pode quebrar o contrato mesmo com o teto de 25%;
- qual é a vantagem do Fail-Fast neste caso;
- qual é o risco de corrigir o teste para aceitar o novo resultado sem discutir a regra de negócio.

**Entregável 2:** previsão antes da execução[✅], tabela de resultados antes e depois da alteração[✅], explicação da regressão e indicação de como o pipeline voltou a ficar verde[✅].


Resultados Antes e Depois da Tabela

- Quando testamos com o desconto de 20 % - (0.20), o teste funciona sem demais intromissões, porém, o mesmo não acontece quando falamos da alteração sugerida de 30% (0.30) quando esta acontesse a execução é interrompida antes mesmo do fim da execução

Explicação da regressão
- Introduzindo um comportamento não planejado em produção, reduzindo a margem de lucro da empresa, pois, atualizar o valor esperado do teste de 80.0 para 75.0 sem consultar a área de negócio oculta um erro de especificação.



## Exercício 3 — pipeline, Matrix Build e cache

Uma pipeline precisa informar não apenas se passou, mas em qual etapa e em qual ambiente ocorreu o problema. Faça alterações nos dados e observe os trade-offs.

In [ ]:
etapas = pd.DataFrame([
    {'ordem': 1, 'etapa': 'Checkout', 'status': 'PASSOU', 'tempo_s': 4},
    {'ordem': 2, 'etapa': 'Instalação de dependências', 'status': 'PASSOU', 'tempo_s': 20},
    {'ordem': 3, 'etapa': 'Linting', 'status': 'PASSOU', 'tempo_s': 8},
    {'ordem': 4, 'etapa': 'Testes unitários', 'status': 'PASSOU', 'tempo_s': 18},
])

print('Etapas do pipeline:')
display(etapas)

matriz = pd.DataFrame([
    {'sistema': 'ubuntu', 'python': '3.10', 'status': 'PASSOU', 'tempo_s': 18},
    {'sistema': 'ubuntu', 'python': '3.11', 'status': 'PASSOU', 'tempo_s': 17},
    {'sistema': 'ubuntu', 'python': '3.12', 'status': 'PASSOU', 'tempo_s': 19},
    {'sistema': 'windows', 'python': '3.10', 'status': 'PASSOU', 'tempo_s': 23},
    {'sistema': 'windows', 'python': '3.11', 'status': 'PASSOU', 'tempo_s': 22},
    {'sistema': 'windows', 'python': '3.12', 'status': 'FALHOU', 'tempo_s': 24},
])

print('Matrix Build:')
display(matriz)

builds = 50
tempo_download_s = 45
tempo_cache_s = 4

tempo_sem_cache_h = builds * tempo_download_s / 3600
tempo_com_cache_h = builds * tempo_cache_s / 3600

print('Horas sem cache:', round(tempo_sem_cache_h, 2))
print('Horas com cache:', round(tempo_com_cache_h, 2))
print('Horas economizadas:', round(tempo_sem_cache_h - tempo_com_cache_h, 2))

Etapas do pipeline:


,ordem,etapa,status,tempo_s
0,1,Checkout,PASSOU,4
1,2,Instalação de dependências,PASSOU,20
2,3,Linting,PASSOU,8
3,4,Testes unitários,PASSOU,18


Matrix Build:


,sistema,python,status,tempo_s
0,ubuntu,3.10,PASSOU,18
1,ubuntu,3.11,PASSOU,17
2,ubuntu,3.12,PASSOU,19
3,windows,3.10,PASSOU,23
4,windows,3.11,PASSOU,22
5,windows,3.12,FALHOU,24


Horas sem cache: 0.62
Horas com cache: 0.06
Horas economizadas: 0.57


### Sua análise

1. Antes de executar, escolha uma combinação da matriz que você acredita ser mais vulnerável a incompatibilidade e explique por quê. Altere apenas o status dessa combinação para FALHOU.

- Combinação mais vulnerável: windows / python 3.12.
Justificativa: Versões mais recentes do Python em sistemas operacionais Windows tendem a apresentar incompatibilidades com bibliotecas que dependem de compilação em C/C++ ou que possuem caminhos de arquivo (paths) e separadores de diretório específicos

2. Depois da alteração, responda: a existência de uma falha impede automaticamente a liberação? O que a equipe precisa investigar antes de decidir?

- A existência de uma falha na matriz não impede automaticamente a liberação para todos os cenários, mas bloqueia o deploy em produção caso a plataforma afetada seja um alvo suportado oficialmente.
A equipe precisa investigar se a falha afeta um ambiente crítico de clientes ou se é um problema pontual de compatibilidade em um ambiente secundário.
O que investigar antes da decisão:
O ambiente que falhou (ex: Windows + Python 3.12) é utilizado por clientes em produção ou é apenas um suporte futuro/
A falha é um bug de código real ou um problema de infraestrutura/ambiente do runner de CI/
É possível lançar uma versão com suporte limitado (hotfix) enquanto a incompatibilidade é corrigida


3. Altere o número de builds para 50 e depois para 1.000. Observe o ganho do cache.

50:

Sem cache:0.62

Com cache:0.06

Horas economizadas:0.57

1000:

Sem cache: 12.5

Com cache: 1.11

Horas Economizadas: 11.39

4. Explique um problema que o cache resolve e um problema que ele não resolve.
Resolve: Reduz o tempo de execução do pipeline ao evitar o download repetitivo de dependências pesadas em cada build, diminuindo custos de computação e acelerando o tempo de feedback para os desenvolvedores.
 NÃO resolve:
As dependências corrompidas, pacotes desatualizados que contêm vulnerabilidades de segurança ou testes quebrados por falhas de lógica de código. Além disso, se a chave de cache for configurada incorretamente, pode mascarar erros ao utilizar artefatos obsoletos.

**Entregável 3:** matriz antes e depois da alteração[✅], previsão comparada com o resultado[✅], análise de 6 a 10 linhas[✅] e cálculo do efeito do cache nos três volumes de build[✅].

## Exercício 4 — métricas DORA e Quality Gate

As métricas abaixo representam deploys de uma equipe. Observe que velocidade e estabilidade precisam ser analisadas juntas.

In [ ]:
deploys = pd.DataFrame([
    {'id': 'DEP-01', 'lead_time_h': 4.5, 'incidente': False, 'recuperacao_min': 0},
    {'id': 'DEP-02', 'lead_time_h': 2.1, 'incidente': False, 'recuperacao_min': 0},
    {'id': 'DEP-03', 'lead_time_h': 8.0, 'incidente': True, 'recuperacao_min': 35},
    {'id': 'DEP-04', 'lead_time_h': 1.5, 'incidente': False, 'recuperacao_min': 0},
    {'id': 'DEP-05', 'lead_time_h': 3.2, 'incidente': False, 'recuperacao_min': 0},
    {'id': 'DEP-06', 'lead_time_h': 12.0, 'incidente': True, 'recuperacao_min': 50},
    {'id': 'DEP-07', 'lead_time_h': 2.8, 'incidente': False, 'recuperacao_min': 0},
    {'id': 'DEP-08', 'lead_time_h': 1.9, 'incidente': False, 'recuperacao_min': 0},
])

def calcular_metricas(df, dias_periodo=14):
    total = len(df)
    falhas = int(df['incidente'].sum())
    recuperacoes = df.loc[df['incidente'], 'recuperacao_min']

    return {
        'deploys_por_dia': round(total / dias_periodo, 2),
        'lead_time_medio_h': round(df['lead_time_h'].mean(), 2),
        'change_failure_rate_percent': round(falhas / total * 100, 2),
        'mttr_medio_min': round(recuperacoes.mean(), 2) if len(recuperacoes) else 0,
    }

metricas_iniciais = calcular_metricas(deploys)
display(pd.DataFrame([metricas_iniciais]))

,deploys_por_dia,lead_time_medio_h,change_failure_rate_percent,mttr_medio_min
0,0.57,4.5,25.0,42.5


In [ ]:
quality_gate = {
    'cobertura_percentual': 86.0,
    'vulnerabilidades_criticas': 0,
    'erros_de_lint': 0,
    'debito_tecnico_h': 0.5,
}

limites = {
    'cobertura_minima': 80.0,
    'debito_tecnico_maximo_h': 1.0,
}

def avaliar_quality_gate(metricas, limites):
    motivos = []
    if metricas['cobertura_percentual'] < limites['cobertura_minima']:
        motivos.append('cobertura abaixo do mínimo')
    if metricas['vulnerabilidades_criticas'] > 0:
        motivos.append('há vulnerabilidade crítica')
    if metricas['erros_de_lint'] > 0:
        motivos.append('há erro bloqueante de lint')
    if metricas['debito_tecnico_h'] > limites['debito_tecnico_maximo_h']:
        motivos.append('débito técnico acima do limite')

    status = 'APROVADO' if not motivos else 'BLOQUEADO'
    return status, motivos

status, motivos = avaliar_quality_gate(quality_gate, limites)
print('Status inicial do Quality Gate:', status)
print('Motivos:', motivos if motivos else 'nenhum')

Status inicial do Quality Gate: APROVADO
Motivos: nenhum


### Sua análise

1. Antes de alterar os dados, preveja o que acontecerá se você acrescentar um deploy bem-sucedido e um deploy com incidente e recuperação de 60 minutos.
2. Faça essa alteração e compare as métricas antes e depois. Qual métrica mudou mais sua percepção sobre a equipe?
3. Altere uma condição do Quality Gate por vez: cobertura abaixo de 80%, uma vulnerabilidade crítica, um erro de lint e débito técnico acima do limite. Registre o status e o motivo em cada caso.
4. Explique por que uma equipe pode ter alta frequência de deploy e ainda assim estar entregando software instável.
5. Diga se o Quality Gate substitui a análise humana. Justifique.

**Entregável 4:** tabela DORA antes e depois, tabela com pelo menos quatro cenários de Quality Gate, previsões comparadas com resultados e uma conclusão de 8 a 12 linhas.

## Checklist de entrega

- [ ] Fiz uma previsão antes de cada alteração.
- [ ] Registrei o que realmente aconteceu.
- [ ] Expliquei causa e consequência, não apenas o número ou status.
- [ ] Entreguei os quatro exercícios e suas tabelas.
- [ ] Analisei pelo menos um trade-off entre velocidade, qualidade e segurança.
- [ ✅] Declarei eventual uso de IA e descrevi como validei o resultado.

Uso de Gemini/ os resultados foram validados no momento da execução no colab.
